"""add columns to table

Revision ID: 2d811136d19c
Revises: be3f72f81f03
Create Date: 2024-10-27 11:42:48.028550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d811136d19c'
down_revision = 'be3f72f81f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
